language: node_js
node_js:
- '0.10'
before_install:
- npm install wintersmith
script:
- wintersmith build
after_success:
- bash ./prepare.sh build/ http://localhost:8080 http://mxklb.github.io/xamblog2013
- bash ./gh-pages-deploy.sh
branches:
  only: master
env:
  global:
  - secure: l15PyHlL7rqxwEUO02uzZU7bW2OhhKZZVwsXBXvZfmCrCRHjVLUZxVOB+ubpTGpeS12/wQZtFxdWimUChkmPrtBtYRy8NEDbZBx0oHKxmQFOp47S2itNneHwCZ01Cuh70TD+9pDvQrTCfHPiszqwwJoDFluYnU4vb5cs/2mjs97bL4vU9e9/a0FzKAmlhKjhs584Ac+4FQgaTy4NdnJmTivsrjGkyVI+dWnP6ZqtdecsxzrENMN3++Abqo5cJ14gzxyAKKF8kvG0OcIGro/vgFJ+Ujn1cL2ysqSlMOmnMNe+zXh7S+HUKjUfcvcxxbtZsnhS3/yWTMyqurtDVUHfNXbMGRcz8wrO1c9W2EhlSJ8aUdDoczvmofEbOZTNFg4yGI5C8+1f92dnSC2TjEfQ/PB8Cbju7MRqKguz/PhSILFE+inSrSr6eDy3ew88BoXuR2+dBCd9aoObTRdoIdjm8Ll9Rlbb1Hmx8IMLYYOyPXJlgw5Vx9PGoeTxZigF1gZhW/J9w6Q6oDqIflKJVEyeligZoHilq3FUUhtWNKeN7ZQSEvtFz4YaTemtSOA5ujlLdkFV/Mi6C90MQ4lr5EyTKAPtnb59a9x1lqoAXp9FCp9h/c81lfYh49vDJCmsZNwnAAl6PZn9Y1PKYf0HlzHEQ5Qtkt8iygJ8l+zqFuVGMCQ=
